### ISSUE TITLE
ActionView::Template::Error: undefined method `<' for nil:NilClass

### ISSUE THREAD

**Issue by nisshiee** [nisshiee/nippo#77]
https://app.getsentry.com/speee/nippoapp/issues/144752916/

```
NoMethodError: undefined method `<' for nil:NilClass
  app/decorators/nippo_decorator.rb:11:in `date_notice'
    elsif reported_for < today && reported_for.friday?
  app/views/shared/nippos/_form.html.slim:13:in `block in _app_views_shared_nippos__form_html_slim___1357197632587472632_47367601181520'
    = @nippo.date_notice
  app/views/shared/nippos/_form.html.slim:1:in `_app_views_shared_nippos__form_html_slim___1357197632587472632_47367601181520'
    = form_for @nippo, class: 'form-horizontal' do |f|
  app/views/nippos/new.html.slim:6:in `_app_views_nippos_new_html_slim___2640381216584647419_47367601697360'
    = render 'shared/nippos/form'
  app/controllers/nippos/previews_controller.rb:10:in `create'
    render 'nippos/new'
...
(131 additional frame(s) were not displayed)

ActionView::Template::Error: undefined method `<' for nil:NilClass

ActionView::Template::Error: undefined method `<' for nil:NilClass
```

validationだけやっても、その後のviewがnilハンドリングしてないのでエラーになる

**Comment by nisshiee** [comment]
![2016-07-23 16 49 07](https://cloud.githubusercontent.com/assets/480925/17076757/6949f4de-50f5-11e6-825f-7af1bc0512d7.png)

released
